apps/blog/urls.py
from django.urls import path
from blog import views
app_name = 'blog'
urlpatterns = [
   path('',views.Article.as_view(), name = 'article')
]

apps/user/urls.py
from django.urls import path
from user import views
app_name = 'user'
urlpatterns = [
    path('', views.Index.as_view(), name ='enter'),
    path('blog/', views.ContextShow.as_view(), name ='blog'),
    # path('intro/', views.Intro.as_view(), name ='intro'),
    # path('article/', views.ContextShow.as_view(), name ='article'),
]

untitled/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('article/',include('blog.urls'))
    # path('user/', include('user_m.urls')),
    # path('', include('verifications.urls')),
]

apps/blog/models.py
from django.db import models
from utils.ModelBases import ModelBase
# Create your models here.

class Tag(models.Model):
    name = models.CharField(verbose_name='标签',help_text='输入标签',max_length=64)
    class Meta:
        verbose_name = '标签'
        db_table = 'db_tag'
        verbose_name_plural = verbose_name

class Article(ModelBase):
    title = models.CharField(verbose_name='文章标题',help_text='文章标题',max_length=150)
    content = models.TextField(verbose_name='文章内容',help_text='文章标题')
    abstract = models.TextField(verbose_name='摘要',help_text='文章标签',default=None)
    click = models.IntegerField(verbose_name='点击量',help_text='点击量',default=0)
    like_num = models.IntegerField(verbose_name='点赞数',help_text='点赞数',default=0)
    tag = models.ForeignKey('Tag',on_delete=models.SET_NULL,null=True)
    class Meta:
        ordering=['-update_time','-id']
        db_table = 'tb_article'
        verbose_name = '文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

class Comments(ModelBase):
    content = models.TextField(verbose_name='评论',help_text='评论')
    author = models.ForeignKey('user.User',on_delete=models.SET_NULL,null=True)
    article = models.ForeignKey('blog.Article',on_delete=models.CASCADE)
    parent = models.ForeignKey('self',on_delete=models.CASCADE,null=True,blank=True)

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = "tb_comment"  # 指明数据库表名
        verbose_name = "评论"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

    def to_dict_data(self):
        comment_dict = {
            'news_id': self.article.id,
            'content_id': self.id,
            'content': self.content,
            'author': self.author.username,
            'update_time': self.update_time.strftime('%Y年%m月%d日 %H:%M'),
            'parent': self.parent.to_dict_data() if self.parent else None,#这个想法是一个递归，这个需要重点掌握。
        }
        return comment_dict

apps/user/models.py
from django.db import models
# from utils import ModelBase
from django.contrib.auth.models import UserManager as _UserManager,AbstractUser
# Create your models here.



class UserManager(_UserManager):
    def create_superuser(self, username, password, email=None, **extra_fields):
        super().create_superuser(username=username,email=email,password=password,**extra_fields)


class User(AbstractUser):
    objects = UserManager()
    REQUIRED_FIELDS = ['mobile']
    mobile = models.CharField(max_length=11,verbose_name='手机号',help_text="手机号",unique=True,
                               error_messages={'unique':"改手机号已注册"})
    email_ac =models.BooleanField(default=False,verbose_name="邮箱状态")
    class Meta:
        db_table ='tb_users'
        verbose_name = '用户'

    def __str__(self):
        return self.username

apps/blog/views.py
from django.shortcuts import render
from django.views import View
# Create your views here.

class Article(View):
    def get(self,request):
        return render(request,'message/articles.html')

apps/user/views.py
from django.shortcuts import render
from django.views import View
import logging
from blog  import models
# Create your views here.
logger = logging.getLogger('django')
class Index(View):
    def get(self,request):
        return render(request, 'index/index.html')


# class Intro(View):
#     def get(self,request):
#         pic_t = ContextImage.objects.only('id','name','text','img_url').filter(is_delete=False)
#         return render(request, 'dco/index.html',context={
#             'pic_t':pic_t
#         })
#
class ContextShow(View):
    def get(self,request):
        article = models.Article.objects.filter(is_delete=False)
        return render(request,'message/index.html',context={
            'article':article
        })

templates/index/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
首页面
{% endblock %}
{% block link %}

{% endblock %}
    <!-- Main -->
	{% block main %}

	    <div id="main">

						{% block intro %}
                    <!-- Intro -->
							<article id="intro">
								<h2 class="major">Intro</h2>
								<span class="image main"><img src="../../static/images/pic01.jpg" alt="" /></span>
								<p>Aenean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. By the way, check out my <a href="#work">awesome work</a>.</p>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel sed vehicula.</p>
							</article>
                    {% endblock %}

                    {% block work %}
                    <!-- Work -->
							<article id="work">
								<h2 class="major">Work</h2>
								<span class="image main"><img src="../../static/images/pic02.jpg" alt="" /></span>
								<p>Adipiscing magna sed dolor elit. Praesent eleifend dignissim arcu, at eleifend sapien imperdiet ac. Aliquam erat volutpat. Praesent urna nisi, fringila lorem et vehicula lacinia quam. Integer sollicitudin mauris nec lorem luctus ultrices.</p>
								<p>Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. Mauris aliquet magna magna sed nunc rhoncus pharetra. Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero. Mauris aliquet magna magna sed nunc rhoncus amet feugiat tempus.</p>
							</article>
                    {% endblock %}

                    {% block about %}
                    <!-- About -->
							<article id="about">
								<h2 class="major">About</h2>
								<span class="image main"><img src="../../static/images/pic03.jpg" alt="" /></span>
								<p>Lorem ipsum dolor sit amet, consectetur et adipiscing elit. Praesent eleifend dignissim arcu, at eleifend sapien imperdiet ac. Aliquam erat volutpat. Praesent urna nisi, fringila lorem et vehicula lacinia quam. Integer sollicitudin mauris nec lorem luctus ultrices. Aliquam libero et malesuada fames ac ante ipsum primis in faucibus. Cras viverra ligula sit amet ex mollis mattis lorem ipsum dolor sit amet.</p>
							</article>
                    {% endblock %}

                    {% block contact %}
                    <!-- Contact -->
							<article id="contact">
								<h2 class="major">Contact</h2>
								<form method="post" action="#">
									<div class="fields">
										<div class="field half">
											<label for="name">Name</label>
											<input type="text" name="name" id="name" />
										</div>
										<div class="field half">
											<label for="email">Email</label>
											<input type="text" name="email" id="email" />
										</div>
										<div class="field">
											<label for="message">Message</label>
											<textarea name="message" id="message" rows="4"></textarea>
										</div>
									</div>
									<ul class="actions">
										<li><input type="submit" value="Send Message" class="primary" /></li>
										<li><input type="reset" value="Reset" /></li>
									</ul>
								</form>
								<ul class="icons">
									<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
									<li><a href="#" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
								</ul>
							</article>
                    {% endblock %}

                    {% block elements %}
                    <!-- Elements -->
							<article id="elements">
								<h2 class="major">Elements</h2>

								<section>
									<h3 class="major">Text</h3>
									<p>This is <b>bold</b> and this is <strong>strong</strong>. This is <i>italic</i> and this is <em>emphasized</em>.
									This is <sup>superscript</sup> text and this is <sub>subscript</sub> text.
									This is <u>underlined</u> and this is code: <code>for (;;) { ... }</code>. Finally, <a href="#">this is a link</a>.</p>
									<hr />
									<h2>Heading Level 2</h2>
									<h3>Heading Level 3</h3>
									<h4>Heading Level 4</h4>
									<h5>Heading Level 5</h5>
									<h6>Heading Level 6</h6>
									<hr />
									<h4>Blockquote</h4>
									<blockquote>Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan faucibus. Vestibulum ante ipsum primis in faucibus lorem ipsum dolor sit amet nullam adipiscing eu felis.</blockquote>
									<h4>Preformatted</h4>
									<pre><code>i = 0;

while (!deck.isInOrder()) {
    print 'Iteration ' + i;
    deck.shuffle();
    i++;
}

print 'It took ' + i + ' iterations to sort the deck.';</code></pre>
								</section>

								<section>
									<h3 class="major">Lists</h3>

									<h4>Unordered</h4>
									<ul>
										<li>Dolor pulvinar etiam.</li>
										<li>Sagittis adipiscing.</li>
										<li>Felis enim feugiat.</li>
									</ul>

									<h4>Alternate</h4>
									<ul class="alt">
										<li>Dolor pulvinar etiam.</li>
										<li>Sagittis adipiscing.</li>
										<li>Felis enim feugiat.</li>
									</ul>

									<h4>Ordered</h4>
									<ol>
										<li>Dolor pulvinar etiam.</li>
										<li>Etiam vel felis viverra.</li>
										<li>Felis enim feugiat.</li>
										<li>Dolor pulvinar etiam.</li>
										<li>Etiam vel felis lorem.</li>
										<li>Felis enim et feugiat.</li>
									</ol>
									<h4>Icons</h4>
									<ul class="icons">
										<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
										<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
										<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
										<li><a href="#" class="icon brands fa-github"><span class="label">Github</span></a></li>
									</ul>

									<h4>Actions</h4>
									<ul class="actions">
										<li><a href="#" class="button primary">Default</a></li>
										<li><a href="#" class="button">Default</a></li>
									</ul>
									<ul class="actions stacked">
										<li><a href="#" class="button primary">Default</a></li>
										<li><a href="#" class="button">Default</a></li>
									</ul>
								</section>

								<section>
									<h3 class="major">Table</h3>
									<h4>Default</h4>
									<div class="table-wrapper">
										<table>
											<thead>
												<tr>
													<th>Name</th>
													<th>Description</th>
													<th>Price</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>Item One</td>
													<td>Ante turpis integer aliquet porttitor.</td>
													<td>29.99</td>
												</tr>
												<tr>
													<td>Item Two</td>
													<td>Vis ac commodo adipiscing arcu aliquet.</td>
													<td>19.99</td>
												</tr>
												<tr>
													<td>Item Three</td>
													<td> Morbi faucibus arcu accumsan lorem.</td>
													<td>29.99</td>
												</tr>
												<tr>
													<td>Item Four</td>
													<td>Vitae integer tempus condimentum.</td>
													<td>19.99</td>
												</tr>
												<tr>
													<td>Item Five</td>
													<td>Ante turpis integer aliquet porttitor.</td>
													<td>29.99</td>
												</tr>
											</tbody>
											<tfoot>
												<tr>
													<td colspan="2"></td>
													<td>100.00</td>
												</tr>
											</tfoot>
										</table>
									</div><div class="tlinks">Collect from <a href="http://www.cssmoban.com/"  title="网站模板">网站模板</a></div>

									<h4>Alternate</h4>
									<div class="table-wrapper">
										<table class="alt">
											<thead>
												<tr>
													<th>Name</th>
													<th>Description</th>
													<th>Price</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>Item One</td>
													<td>Ante turpis integer aliquet porttitor.</td>
													<td>29.99</td>
												</tr>
												<tr>
													<td>Item Two</td>
													<td>Vis ac commodo adipiscing arcu aliquet.</td>
													<td>19.99</td>
												</tr>
												<tr>
													<td>Item Three</td>
													<td> Morbi faucibus arcu accumsan lorem.</td>
													<td>29.99</td>
												</tr>
												<tr>
													<td>Item Four</td>
													<td>Vitae integer tempus condimentum.</td>
													<td>19.99</td>
												</tr>
												<tr>
													<td>Item Five</td>
													<td>Ante turpis integer aliquet porttitor.</td>
													<td>29.99</td>
												</tr>
											</tbody>
											<tfoot>
												<tr>
													<td colspan="2"></td>
													<td>100.00</td>
												</tr>
											</tfoot>
										</table>
									</div>
								</section>

								<section>
									<h3 class="major">Buttons</h3>
									<ul class="actions">
										<li><a href="#" class="button primary">Primary</a></li>
										<li><a href="#" class="button">Default</a></li>
									</ul>
									<ul class="actions">
										<li><a href="#" class="button">Default</a></li>
										<li><a href="#" class="button small">Small</a></li>
									</ul>
									<ul class="actions">
										<li><a href="#" class="button primary icon solid fa-download">Icon</a></li>
										<li><a href="#" class="button icon solid fa-download">Icon</a></li>
									</ul>
									<ul class="actions">
										<li><span class="button primary disabled">Disabled</span></li>
										<li><span class="button disabled">Disabled</span></li>
									</ul>
								</section>

								<section>
									<h3 class="major">Form</h3>
									<form method="post" action="#">
										<div class="fields">
											<div class="field half">
												<label for="demo-name">Name</label>
												<input type="text" name="demo-name" id="demo-name" value="" placeholder="Jane Doe" />
											</div>
											<div class="field half">
												<label for="demo-email">Email</label>
												<input type="email" name="demo-email" id="demo-email" value="" placeholder="jane@abc.com" />
											</div>
											<div class="field">
												<label for="demo-category">Category</label>
												<select name="demo-category" id="demo-category">
													<option value="">-</option>
													<option value="1">Manufacturing</option>
													<option value="1">Shipping</option>
													<option value="1">Administration</option>
													<option value="1">Human Resources</option>
												</select>
											</div>
											<div class="field half">
												<input type="radio" id="demo-priority-low" name="demo-priority" checked>
												<label for="demo-priority-low">Low</label>
											</div>
											<div class="field half">
												<input type="radio" id="demo-priority-high" name="demo-priority">
												<label for="demo-priority-high">High</label>
											</div>
											<div class="field half">
												<input type="checkbox" id="demo-copy" name="demo-copy">
												<label for="demo-copy">Email me a copy</label>
											</div>
											<div class="field half">
												<input type="checkbox" id="demo-human" name="demo-human" checked>
												<label for="demo-human">Not a robot</label>
											</div>
											<div class="field">
												<label for="demo-message">Message</label>
												<textarea name="demo-message" id="demo-message" placeholder="Enter your message" rows="6"></textarea>
											</div>
										</div>
										<ul class="actions">
											<li><input type="submit" value="Send Message" class="primary" /></li>
											<li><input type="reset" value="Reset" /></li>
										</ul>
									</form>
								</section>

							</article>
                    {% endblock %}
					</div>
	{% endblock %}


<!-- Footer -->
					<footer id="footer">
						<p class="copyright">&copy;姜昊良<a href="http://www.cssmoban.com/" target="_blank" title=""></a>  <a href="#" title="block">坚持</a></p>
					</footer>


		<!-- BG -->
			<div id="bg"></div>

        {% block script %}

        {% endblock %}

templates/index/intro.html

{% extends 'base/tanzhou/base.html' %}
{% block title %}文档下载{% endblock %}
{% block link %}
      <link rel="stylesheet" href="../../static/css/doc/docDownload.css">

{% endblock %}

{% block main-contain %}

<div class="main-contain ">
    <div class="banner">
      <img src="/media/doc_banner_2.jpg"
           alt="">
    </div>
    <div class="pay-doc-contain">
      <ul class="pay-list">

        {% for doc in docs %}

          <li class="pay-item">
{#          <div class="pay-img doc"></div>#}
            <img src="{{ doc.image_url }}" class="pay-img doc"/>
          <div class="d-contain">
            <p class="doc-title">{{ doc.title }}</p>
            <p class="doc-desc">{{ doc.desc }}</p>

            <a href="{% url 'doc:doc_download' doc.id %}" class="pay-price">下载</a>
          </div>
        </li>

        {% endfor %}

      </ul>
    </div>
  </div>

{% endblock %}

templates/index/login.html
{% extends 'base/base.html' %}
{% load static %}

    {% block title %}
    登入页面
    {% endblock %}

    {% block link %}
    <link rel="stylesheet" href="../../static/css/authPro/auth.css">
    {% endblock %}


{% block main %}
<main id="container">
  <div class="login-contain">
    <div class="top-contain">
      <h4 class="please-login">请登录</h4>
      <a href="javascript:void(0);" class="register">立即注册 &gt;</a>
    </div>
    <form action="" method="post" class="form-contain">
        {% csrf_token %}
      <div class="form-item">
        <input type="tel" placeholder="请输入手机号或用户名" name="telephone" class="form-control" autocomplete="off">
      </div>
      <div class="form-item">
        <input type="password" placeholder="请输入密码" name="password" class="form-control">
      </div>
      <div class="form-item clearfix">
        <label>
          <input type="checkbox" name="remember">
          <span>记住我</span>
        </label>
        <a href="javascript:void(0);" class="forget-password">忘记密码?</a>
      </div>
      <div class="form-login">
        <input type="submit" value="登录" class="login-btn">
      </div>
    </form>
  </div>
</main>
{% endblock %}

{% block script %}
    <script src="{% static "/css/js/users/login.js" %}"></script>
{% endblock %}



templates/index/register.html
{% extends 'base/tanzhou/base.html' %}

{% load static %}#自定义静态文件是要加这个的，而且是必须加。
{% block title %}
    注册页面
{% endblock %}


{% block link %}
<link rel="stylesheet" href="../../static/css/authPro/auth.css">
{% endblock %}


{% block main %}
<main id="container" >
  <div class="register-contain" style="height: 500px;">
    <div class="top-contain">
      <h4 class="please-register">请注册</h4>
      <a href="javascript:void(0);" class="login">立即登录 &gt;</a>
    </div>
    <form action="" method="post" class="form-contain">
        {% csrf_token %}
      <div class="form-item">
        <input type="text" placeholder="请输入用户名" id="user_name" name="username" class="form-control" autocomplete="off">
      </div>
      <div class="form-item">
        <input type="password" placeholder="请输入密码" id="pwd" name="password" class="form-control">
      </div>
      <div class="form-item">
        <input type="password" placeholder="请输入确认密码" name="password_repeat" class="form-control">
      </div>
      <div class="form-item">
        <input type="tel" placeholder="请输入手机号" id="mobile" name="telephone" class="form-control" autocomplete="off" autofocus>
      </div>
      <div class="form-item">
        <input type="text" placeholder="请输入图形验证码" id="input_captcha" name="captcha_graph" class="form-captcha">
        <a href="javascript:void(0);" class="captcha-graph-img">
          <img src="" alt="验证码" title="点击刷新">
        </a>
      </div>
      <div class="form-item">
        <input type="submit" value="立即注册" class="register-btn">
      </div>
        <div><a href="{% url 'user:enter' %}" style="color: cadetblue;font-size: 20px">返回</a></div>
    </form>
  </div>
</main>
{% endblock %}


{% block script %}
    <script src="{% static 'css/js/users/auth.js' %}"></script>
{% endblock %}

templates/index/test.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}

测试页面
{% endblock %}
{% block link %}
     <link rel="stylesheet" href="../../static/css/doc/docDownload.css">
     {% endblock %}
{% block header %}
{% endblock%}
{% block main %}

{% endblock %}

templates/message/articles.html
{% extends 'message/index.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="../../static/css/news_detail/news-detail.css" type="text/css">
{% endblock %}
{% block articles %}
<div class="news-contain" style="position: relative;left: 150px;">

      <h1 class="news-title">{{ news.title }}</h1>
      <div class="news-info">
        <div class="news-info-left">
          <span class="news-author">{{ news.author.username }}</span>
          <span class="news-pub-time">{{ news.update_time }}</span>
          <span class="news-type">{{ news.tag.name }}</span>
        </div>
      </div>
      <article class="news-content">
        {{ news.content | safe }}
      </article>
      <div class="comment-contain">
        <div class="comment-pub clearfix">
          <div class="new-comment" style="color: white">
            文章评论(<span class="comment-count">0</span>)
          </div>
          <div class="comment-control please-login-comment" style="display:none;">
            <input type="text" placeholder="请登录后参加评论">
          </div>
          <div class="comment-control logged-comment">
            <input type="text" placeholder="请填写评论">
          </div>
          <button class="comment-btn">发表评论</button>
        </div>
        <ul class="comment-list">
          <li class="comment-item">
            <div class="comment-info clearfix">
              <img src="" alt="avatar" class="comment-avatar">
              <span class="comment-user">评论人</span>
              <span class="comment-pub-time">1小时前</span>
            </div>
            <div class="comment-content">这是一条评论</div>
          </li>
          <li class="comment-item">
            <div class="comment-info clearfix">
              <img src="" alt="avatar" class="comment-avatar">
              <span class="comment-user">评论人</span>
              <span class="comment-pub-time">1小时前</span>
            </div>
            <div class="comment-content">这是一条评论</div>
          </li>
        </ul>
      </div>

    </div>

{% endblock %}


templates/message/index.html
<!DOCTYPE HTML>
<html style="background-image: url('../../static/images/blog_bcg/b_2.jpg');background-size:cover;">
	<head>
		<title>Home</title>

        <link rel="stylesheet" href="../../static/css/css_reset.css" type="text/css">
		<link href="../../static/css/stylee.css" rel="stylesheet" type="text/css"  media="all" />\
        {% block link %}{% endblock %}
        <style type="text/css">
            .headers {
                position: relative;
                left: 36%;
            }
            .headers ul li{
                float: left;
                margin: 20px 20px ;
            }
            .headers:after{
				/*添加一个内容*/
				content: "";
				/*转换为一个块元素*/
				display: block;
				/*清除两侧的浮动*/
				clear: both;
			}
            .content{
                position: relative;
                left: 5%;
            }
            .artical-box{
                position: relative;
            }
            .artical-box .artical_title{
                    {#border: 1px solid black;#}
                    height: 35px;
                    width: 50%;
            }
            .artical-box .artical_title span{
                margin-left: 5px;
            }
            .artical-box .title_tag{
                {#border: 1px solid white;#}
                height: 30px;
                display: block;
                font-size: 24px;
                color: gray;
                {#align-content: center;#}
            }

            .artical-box .artical_contents{
                {#border: 1px solid black;#}
                width: 100%;
                color: white;
                text-indent:2em;
            }
            .artical-box .artical_tail{
                {#border: 1px solid black;#}
                width: 100%;{# 为了架构好看先这样写 #}


            }
            .artical-box .artical_tail ul li{
                float: left;
                margin: 10px;
            }
            .clearbox:after{
                content: "";
				display: block;
				clear: both;
            }

        </style>
	</head>
	<body >
		<!---start-wrap--->
		<div class="wrap" style="background-color: transparent;">
			<!---start-header--->
			<div class="header">
				<!---start-logo--->
			</div>
			<!---End-header--->

			<!---start-main---->
        {% block main %}
        <div class="main">
            {% block content %}
            <!---start-Content---->
{#                一页只显示四条#}
				<div class="content">
					<div class="image-slider">
						  <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
						  <script src="../../static/css/js/jquery.slides.min.js"></script>
					</div>
					<div class="clear"> </div>
                    <div class = "headers">
                        <ul>
                            <li><a href="{% url 'user:enter' %}" style="font-size: 30px; display: block;position:relative;left: 65%">首页</a></li>
                            <li><a href="{% url 'user:blog' %}" style="font-size: 30px; display: block;position:relative;left: 65%">&nbsp;&nbsp;博客</a></li>
                            <li><a href="#" style="font-size: 30px; display: block;position:relative;left: 65%">资源下载</a></li>
                            <div id="clear_box"></div>
                        </ul>
                    </div>
                    <hr style="position: relative;left: 145px">
                {% block articles %}
                 {% for c in article %}
                        <div class="Latest-news">
						<div class="Latest-news-title">
							<h5> </h5>
							<div class="clear"> </div>
						</div>
						<div class="blog-articals">
							<div class="artical"  style="position:relative; left: 150px">
								<div class="artical-heading">

								</div>
                                <a href="{% url 'blog:article' %}">
                                    <div class="artical-box" >
                                        <div class="artical_title">
                                            <span class="title_tag">{{c.tag.name}}<span class="title_besider">{{c.title}}</span></span>

                                        </div>
                                        <div class="artical_contents">{{ c.abstract }}</div>
                                        <div class="artical_tail">
                                            <ul>
                                                <li>{{ c.create_time}}</li>
                                                <li>|</li>
                                                <li>阅读数&nbsp;{{ c.click }} <span></span></li>
                                                <li>|</li>
                                                <li>点赞数 {{ c.like_num }}</li>
                                                <div class="clearbox"></div>
                                            </ul>
                                        </div>

									    <div class="clear"> </div>
								    </div>
                                </a>

							</div>
						</div><div class="tlinks">Collect from <a href="http://www.cssmoban.com/" >网页模板</a></div>


					</div>
                    {% endfor %}
                {% endblock %}


                    <a class="button" href="{% url 'user:enter' %}" style="position: relative;left: 150px;">返回首页</a>


				</div>
				<!---End-Content---->

            {% endblock %}



				<!---start-sidebar---->
            <div class="side-boxs" style="position: relative;height: 1000px;width: 49%;left: -390px">
                <div class="personal_box common-side">
{#                    ../../static/images/touxiang/avatar.jpeg#}
                    <div class="image_box"><a href="#"><img src="../../static/images/touxiang/avatar.jpeg" alt=""></a><span style="color: black;font-size:35px;display: block;position: absolute;top: 20%;left: 30%;">姜昊良</span></div>
                    <div class="statistics_num">
                        <span>文章数:</span>&nbsp;<span>获赞数:</span>
                    </div>
                    <div></div>
                    <div></div>
                </div>
                <div class="time_show common-side" style="position: absolute;height: 243px;width: 350px;border: 1px solid white;left: 200px;top: 35%;">

                </div>
                <div></div>
                <div></div>
                <div></div>
                <!---end-sidebar---->
            </div>


			</div>

			</div>
        {% endblock %}
        <!---End-main---->


		<!---End-wrap--->
	
</body>
</html>